export default {
    LOGIN_USERNAME_CHANGE: 'LOGIN_USERNAME_CHANGE',
    LOGIN_PASSWORD_CHANGE: 'LOGIN_PASSWORD_CHANGE',
    LOGIN_SET_LOADING: 'LOGIN_SET_LOADING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_DO_LOGOUT: 'LOGIN_DO_LOGOUT',
    LOGIN_DO_LOGIN: 'LOGIN_DO_LOGIN',
    HOME_SEARCH_VALUE_CHANGE: 'HOME_SEARCH_VALUE_CHANGE',
    HOME_UPDATE_INPUT_VALUE: 'HOME_UPDATE_INPUT_VALUE',
    HOME_UPDATE_OPTIONS: 'HOME_UPDATE_OPTIONS',
    HOME_SET_ERROR: 'HOME_SET_ERROR',
    HOME_SET_NO_RESULT: 'HOME_SET_NO_RESULT'

}
